"""Data models for the QMCP agent framework.

This module provides all data models organized into logical submodules:
- base: Utilities and common imports
- enums: All enumerations
- configs: Configuration models
- entities: Database table models
- schemas: API request/response schemas
"""

from .base import utc_now, generate_uuid, validate_identifier

from .enums import (
    AgentRole,
    AggregationMethod,
    AuthScope,
    CommunicationProtocol,
    ConsensusMethod,
    ErrorStrategy,
    EventType,
    ExecutionStatus,
    HealthStatus,
    LogLevel,
    MessageType,
    ModelAvailability,
    ModelCapabilityType,
    ModelFamily,
    ModelProvider,
    ModelTier,
    PricingUnit,
    Priority,
    ResourceType,
    SkillCategory,
    TopologyType,
)

from .configs import (
    AgentCapability,
    AgentConfig,
    ChainOfCommandConfig,
    CheckpointConfig,
    CommunicationConfig,
    CompoundConfig,
    CrossCheckConfig,
    DebateConfig,
    DelegationConfig,
    EnsembleConfig,
    LoggingConfig,
    MeshConfig,
    MetricsConfig,
    ModelCapabilities,
    ModelConfig,
    ModelEndpoint,
    ModelFallbackConfig,
    ModelLimits,
    ModelPricing,
    ModelRegistryEntry,
    ModelSamplingParams,
    PipelineConfig,
    ResourceLimits,
    RetryConfig,
    RingConfig,
    SecurityConfig,
    SkillConfig,
    StarConfig,
    TimeoutConfig,
)

from .entities import (
    AgentInstance,
    AgentSkill,
    AgentType,
    AuditLog,
    Checkpoint,
    Execution,
    Message,
    MetricRecord,
    ResourceAllocation,
    Result,
    ToolInvocation,
    Topology,
    TopologyMembership,
    WorkflowTemplate,
)

from .registry import Models

from .schemas import (
    AgentInstanceRead,
    AgentInstanceSummary,
    AgentTypeCreate,
    AgentTypeRead,
    AgentTypeSummary,
    AgentTypeUpdate,
    AuditLogRead,
    CheckpointRead,
    ExecutionCreate,
    ExecutionRead,
    ExecutionStatusUpdate,
    ExecutionSummary,
    FilterParams,
    HealthCheck,
    MessageCreate,
    MessageRead,
    MetricAggregation,
    MetricCreate,
    MetricRead,
    PaginatedResponse,
    PaginationParams,
    ResultCreate,
    ResultRead,
    SkillCreate,
    SkillRead,
    SortParams,
    SystemStats,
    ToolInvocationCreate,
    ToolInvocationRead,
    TopologyCreate,
    TopologyRead,
    TopologySummary,
    TopologyUpdate,
    WorkflowTemplateCreate,
    WorkflowTemplateRead,
    WorkflowTemplateUpdate,
)

__all__ = [
    # Base utilities
    "utc_now",
    "generate_uuid",
    "validate_identifier",
    # Enums
    "AgentRole",
    "AggregationMethod",
    "AuthScope",
    "CommunicationProtocol",
    "ConsensusMethod",
    "ErrorStrategy",
    "EventType",
    "ExecutionStatus",
    "HealthStatus",
    "LogLevel",
    "MessageType",
    "ModelAvailability",
    "ModelCapabilityType",
    "ModelFamily",
    "ModelProvider",
    "ModelTier",
    "PricingUnit",
    "Priority",
    "ResourceType",
    "SkillCategory",
    "TopologyType",
    # Model Registry
    "Models",
    # Model Configs
    "ModelCapabilities",
    "ModelConfig",
    "ModelEndpoint",
    "ModelFallbackConfig",
    "ModelLimits",
    "ModelPricing",
    "ModelRegistryEntry",
    "ModelSamplingParams",
    # Configs
    "AgentCapability",
    "AgentConfig",
    "ChainOfCommandConfig",
    "CheckpointConfig",
    "CommunicationConfig",
    "CompoundConfig",
    "CrossCheckConfig",
    "DebateConfig",
    "DelegationConfig",
    "EnsembleConfig",
    "LoggingConfig",
    "MeshConfig",
    "MetricsConfig",
    "PipelineConfig",
    "ResourceLimits",
    "RetryConfig",
    "RingConfig",
    "SecurityConfig",
    "SkillConfig",
    "StarConfig",
    "TimeoutConfig",
    # Entities
    "AgentInstance",
    "AgentSkill",
    "AgentType",
    "AuditLog",
    "Checkpoint",
    "Execution",
    "Message",
    "MetricRecord",
    "ResourceAllocation",
    "Result",
    "ToolInvocation",
    "Topology",
    "TopologyMembership",
    "WorkflowTemplate",
    # Schemas
    "AgentInstanceRead",
    "AgentInstanceSummary",
    "AgentTypeCreate",
    "AgentTypeRead",
    "AgentTypeSummary",
    "AgentTypeUpdate",
    "AuditLogRead",
    "CheckpointRead",
    "ExecutionCreate",
    "ExecutionRead",
    "ExecutionStatusUpdate",
    "ExecutionSummary",
    "FilterParams",
    "HealthCheck",
    "MessageCreate",
    "MessageRead",
    "MetricAggregation",
    "MetricCreate",
    "MetricRead",
    "PaginatedResponse",
    "PaginationParams",
    "ResultCreate",
    "ResultRead",
    "SkillCreate",
    "SkillRead",
    "SortParams",
    "SystemStats",
    "ToolInvocationCreate",
    "ToolInvocationRead",
    "TopologyCreate",
    "TopologyRead",
    "TopologySummary",
    "TopologyUpdate",
    "WorkflowTemplateCreate",
    "WorkflowTemplateRead",
    "WorkflowTemplateUpdate",
]
