"""Which models belong to the server database, declared once.

`SQLModel.metadata` IS GLOBAL AND HOLDS MORE THAN ONE DATABASE. Importing any
module that declares a table registers it there, and this repository has two
unrelated sets:

  the server database   `qmcp.db` -- tool invocations, human requests, the
                        agent framework's entities
  a flow database       `qmcp.cookbook.persistence`, whose `FlowPersistence`
                        takes a `db_path` per run and creates `flowrun`,
                        `agentrun`, `mcpinvocation`, `artifact` and
                        `checklistitem` in whatever file it was handed

Reading the whole metadata as "the server's schema" is therefore wrong, and
wrong in a way that only shows up when something has imported the cookbook.
A drift check written that way reports five tables missing from `qmcp.db` that
were never meant to be in it; an autogenerated migration written that way would
*add* them.

That is the same defect as two models sharing one table name, one layer up: a
global namespace holding two things, resolved by import order.

SO THE LIST IS DECLARED, NOT DISCOVERED. `alembic/env.py` imports exactly these
modules and `qmcp.db.schema` compares exactly their tables. A model file added
to the server and not added here is invisible to both -- which is a gap, and a
quieter one than the alternative, so `qm db drift` says what it compared.
"""

from __future__ import annotations

SERVER_MODEL_MODULES: tuple[str, ...] = (
    "qmcp.db.models",
    "qmcp.agentframework.models.entities.agents",
    "qmcp.agentframework.models.entities.audit",
    "qmcp.agentframework.models.entities.executions",
    "qmcp.agentframework.models.entities.messages",
    "qmcp.agentframework.models.entities.resources",
    "qmcp.agentframework.models.entities.topologies",
    "qmcp.agentframework.models.entities.workflows",
)


def import_server_models() -> None:
    """Import every module above, populating `SQLModel.metadata`."""
    import importlib

    for name in SERVER_MODEL_MODULES:
        importlib.import_module(name)


def server_table_names() -> set[str]:
    """The table names those modules declare.

    Read from the model classes rather than the metadata, because a class knows
    which module defined it and a `Table` does not.
    """
    from sqlmodel import SQLModel

    import_server_models()

    def descendants(cls):
        for sub in cls.__subclasses__():
            yield sub
            yield from descendants(sub)

    names: set[str] = set()
    for model in descendants(SQLModel):
        table = getattr(model, "__table__", None)
        if table is None:
            continue
        if getattr(model, "__module__", "") in SERVER_MODEL_MODULES:
            names.add(table.name)
    return names


def server_metadata():
    """Metadata holding only the server's tables.

    Used as alembic's `target_metadata` so that a stray import of the cookbook
    cannot leak a flow table into a server migration.
    """
    from sqlalchemy import MetaData
    from sqlmodel import SQLModel

    wanted = server_table_names()
    scoped = MetaData(naming_convention=SQLModel.metadata.naming_convention)
    for name, table in SQLModel.metadata.tables.items():
        if name in wanted:
            table.to_metadata(scoped)
    return scoped
