"""
QMCP Agent Framework

A hierarchical, mixin-capable framework for organizing LLM agent types
with support for various collaboration topologies.
"""

from qmcp.agentframework.mixins import (
    BaseMixin,
    HumanInLoopConfig,
    HumanInLoopMixin,
    MemoryConfig,
    MemoryMixin,
    MixinConfig,
    MixinRegistry,
    ReasoningConfig,
    ReasoningMixin,
    StructuredOutputConfig,
    StructuredOutputMixin,
    ToolUseConfig,
    ToolUseMixin,
    mixin,
)
from qmcp.agentframework.models import (
    AgentCapability,
    AgentConfig,
    AgentInstance,
    AgentRole,
    AgentType,
    AggregationMethod,
    ChainOfCommandConfig,
    CompoundConfig,
    ConsensusMethod,
    CrossCheckConfig,
    DebateConfig,
    DelegationConfig,
    EnsembleConfig,
    Execution,
    ExecutionStatus,
    Message,
    MessageType,
    PipelineConfig,
    Result,
    Topology,
    TopologyMembership,
    TopologyType,
)
from qmcp.agentframework.runners import (
    AsyncRunner,
    BaseRunner,
    LocalRunner,
    MetaflowRunner,
    RunConfig,
    RunnerRegistry,
    RunResult,
    runner,
)
from qmcp.agentframework.topologies import (
    AgentInvocationResult,
    BaseTopology,
    ChainOfCommandTopology,
    CompoundTopology,
    CrossCheckTopology,
    DebateTopology,
    DelegationTopology,
    EnsembleTopology,
    ExecutionContext,
    PipelineTopology,
    TopologyRegistry,
    topology,
)

__version__ = "0.1.0"
__all__ = [
    # Version
    "__version__",
    # Enums
    "AgentRole",
    "TopologyType",
    "ExecutionStatus",
    "MessageType",
    "ConsensusMethod",
    "AggregationMethod",
    # Config models
    "AgentCapability",
    "AgentConfig",
    "DebateConfig",
    "ChainOfCommandConfig",
    "DelegationConfig",
    "CrossCheckConfig",
    "EnsembleConfig",
    "PipelineConfig",
    "CompoundConfig",
    # Table models
    "AgentType",
    "AgentInstance",
    "Topology",
    "TopologyMembership",
    "Execution",
    "Message",
    "Result",
    # Mixins
    "BaseMixin",
    "MixinConfig",
    "MixinRegistry",
    "mixin",
    "ToolUseMixin",
    "ToolUseConfig",
    "MemoryMixin",
    "MemoryConfig",
    "ReasoningMixin",
    "ReasoningConfig",
    "HumanInLoopMixin",
    "HumanInLoopConfig",
    "StructuredOutputMixin",
    "StructuredOutputConfig",
    # Topologies
    "ExecutionContext",
    "AgentInvocationResult",
    "BaseTopology",
    "TopologyRegistry",
    "topology",
    "DebateTopology",
    "ChainOfCommandTopology",
    "DelegationTopology",
    "CrossCheckTopology",
    "EnsembleTopology",
    "PipelineTopology",
    "CompoundTopology",
    # Runners
    "RunConfig",
    "RunResult",
    "BaseRunner",
    "RunnerRegistry",
    "runner",
    "LocalRunner",
    "AsyncRunner",
    "MetaflowRunner",
]
