"""baseline: the schema this database already has

Revision ID: 3dda531e16d2
Revises: 
Create Date: 2026-08-17 22:42:42.068160
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# Reflected from a SQLite database, so the column types it produced are the
# dialect's own. Without this import the revision raises NameError part-way
# through `upgrade`, which is the worst place to discover a missing import.
from sqlalchemy.dialects import sqlite

revision: str = '3dda531e16d2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('role', sa.VARCHAR(length=11), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('config', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_types', schema=None) as batch_op:
        batch_op.create_index('ix_agent_types_name', ['name'], unique=1)

    op.create_table('human_requests',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(), nullable=False),
    sa.Column('prompt', sa.VARCHAR(), nullable=False),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_requests', schema=None) as batch_op:
        batch_op.create_index('ix_human_requests_correlation_id', ['correlation_id'], unique=False)
        batch_op.create_index('ix_human_requests_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_human_requests_request_type', ['request_type'], unique=False)
        batch_op.create_index('ix_human_requests_status', ['status'], unique=False)

    op.create_table('human_responses',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('request_id', sa.VARCHAR(), nullable=False),
    sa.Column('response', sa.VARCHAR(), nullable=False),
    sa.Column('response_metadata', sqlite.JSON(), nullable=True),
    sa.Column('responded_by', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_responses', schema=None) as batch_op:
        batch_op.create_index('ix_human_responses_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_human_responses_request_id', ['request_id'], unique=False)

    op.create_table('tool_invocations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), nullable=False),
    sa.Column('input_params', sqlite.JSON(), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index('ix_tool_invocations_correlation_id', ['correlation_id'], unique=False)
        batch_op.create_index('ix_tool_invocations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_tool_invocations_tool_name', ['tool_name'], unique=False)

    op.create_table('topologies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('topology_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('config', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.create_index('ix_topologies_name', ['name'], unique=1)

    op.create_table('agent_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_type_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('category', sa.VARCHAR(length=13), nullable=False),
    sa.Column('proficiency', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('topology_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('input_data', sqlite.JSON(), nullable=False),
    sa.Column('output_data', sqlite.JSON(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('error_details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_executions_correlation_id', ['correlation_id'], unique=False)

    op.create_table('topology_memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topology_id', sa.INTEGER(), nullable=False),
    sa.Column('agent_type_id', sa.INTEGER(), nullable=False),
    sa.Column('slot_name', sa.VARCHAR(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('config_overrides', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('topology_id', sa.INTEGER(), nullable=False),
    sa.Column('default_input', sqlite.JSON(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_templates_name', ['name'], unique=1)

    op.create_table('agent_instances',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_type_id', sa.INTEGER(), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=True),
    sa.Column('state', sqlite.JSON(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_active', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state_snapshot', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_allocations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('acquired_at', sa.DATETIME(), nullable=False),
    sa.Column('released_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tool_invocations',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=True),
    sa.Column('agent_instance_id', sa.CHAR(length=32), nullable=True),
    sa.Column('tool_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('input_data', sqlite.JSON(), nullable=False),
    sa.Column('output_data', sqlite.JSON(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=512), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('invoked_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=True),
    sa.Column('agent_instance_id', sa.CHAR(length=32), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('level', sa.VARCHAR(length=8), nullable=False),
    sa.Column('message', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=32), nullable=False),
    sa.Column('recipient_id', sa.CHAR(length=32), nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('round_number', sa.INTEGER(), nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['agent_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_records',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_instance_id', sa.CHAR(length=32), nullable=True),
    sa.Column('metric_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=32), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('execution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('agent_instance_id', sa.CHAR(length=32), nullable=False),
    sa.Column('output', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('reasoning', sa.VARCHAR(), nullable=True),
    sa.Column('token_usage', sqlite.JSON(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('metric_records')
    op.drop_table('messages')
    op.drop_table('audit_logs')
    op.drop_table('agent_tool_invocations')
    op.drop_table('resource_allocations')
    op.drop_table('checkpoints')
    op.drop_table('agent_instances')
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_templates_name')

    op.drop_table('workflow_templates')
    op.drop_table('topology_memberships')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index('ix_executions_correlation_id')

    op.drop_table('executions')
    op.drop_table('agent_skills')
    with op.batch_alter_table('topologies', schema=None) as batch_op:
        batch_op.drop_index('ix_topologies_name')

    op.drop_table('topologies')
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_invocations_tool_name')
        batch_op.drop_index('ix_tool_invocations_created_at')
        batch_op.drop_index('ix_tool_invocations_correlation_id')

    op.drop_table('tool_invocations')
    with op.batch_alter_table('human_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_human_responses_request_id')
        batch_op.drop_index('ix_human_responses_created_at')

    op.drop_table('human_responses')
    with op.batch_alter_table('human_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_human_requests_status')
        batch_op.drop_index('ix_human_requests_request_type')
        batch_op.drop_index('ix_human_requests_created_at')
        batch_op.drop_index('ix_human_requests_correlation_id')

    op.drop_table('human_requests')
    with op.batch_alter_table('agent_types', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_types_name')

    op.drop_table('agent_types')
    # ### end Alembic commands ###
