"""Alembic environment for qmcp.

THE URL IS DERIVED, NEVER CONFIGURED TWICE. `alembic.ini` deliberately sets no
`sqlalchemy.url`. It comes from `qmcp.config.get_settings()` -- the same setting
the application reads -- so a migration cannot be run against one database while
the server talks to another because somebody edited one file and not the other.

THE DRIVER IS STRIPPED. The application uses `sqlite+aiosqlite`, which is an
async driver; alembic's migration context is synchronous. The `+aiosqlite` is
removed to give a plain `sqlite://` URL over the *same file*. Doing this by
string replacement on the whole URL would be fragile, so the path is resolved by
`qmcp.db.paths.database_file` -- the one place that knows a SQLAlchemy URL is
not a filename.

EVERY MODEL MODULE IS IMPORTED BEFORE `target_metadata` IS READ. Autogenerate
compares the database against `SQLModel.metadata`, which is populated as a side
effect of importing model modules. Importing only some of them produces a
migration that silently drops every table it did not see -- so the imports below
are load-bearing, not tidy-up, and `--autogenerate` is only as complete as they
are.
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sqlmodel import SQLModel  # noqa: E402

from qmcp.config import get_settings  # noqa: E402
from qmcp.db.paths import database_file  # noqa: E402
from qmcp.db.registry import server_metadata  # noqa: E402

# Load-bearing imports: see the module docstring. Each populates
# `SQLModel.metadata`, and a missing one becomes a dropped table in an
# autogenerated revision.
import qmcp.db.models  # noqa: E402,F401
import qmcp.agentframework.models.entities.agents  # noqa: E402,F401
import qmcp.agentframework.models.entities.audit  # noqa: E402,F401
import qmcp.agentframework.models.entities.executions  # noqa: E402,F401
import qmcp.agentframework.models.entities.messages  # noqa: E402,F401
import qmcp.agentframework.models.entities.resources  # noqa: E402,F401
import qmcp.agentframework.models.entities.topologies  # noqa: E402,F401
import qmcp.agentframework.models.entities.workflows  # noqa: E402,F401

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

def _baseline_metadata():
    """Reflected metadata from an existing database, when one is named.

    `QMCP_BASELINE_FROM=<path> alembic revision --autogenerate` describes *that
    database* rather than the models. It exists so the first revision can be the
    schema a real database already has -- which is what makes `alembic stamp`
    honest on it -- and so that baseline is reproducible by anyone instead of
    being a file somebody hand-wrote once.

    Unset, which is every ordinary run, this returns None and the models are
    used as normal.
    """
    source = os.environ.get("QMCP_BASELINE_FROM")
    if not source:
        return None
    from sqlalchemy import MetaData, create_engine

    reflected = MetaData()
    engine = create_engine(f"sqlite:///{Path(source).as_posix()}")
    try:
        reflected.reflect(bind=engine)
    finally:
        engine.dispose()
    return reflected


target_metadata = _baseline_metadata() or server_metadata()

# A NAMING CONVENTION, BECAUSE SQLITE MIGRATIONS RUN IN BATCH MODE. SQLite
# cannot ALTER a constraint, so alembic rebuilds the table around the change --
# and to rebuild a constraint it has to be able to name it. Without a
# convention, autogenerate emits `create_foreign_key(None, ...)`, which raises
# `ValueError: Constraint must have a name` *after* earlier statements in the
# same migration have committed, leaving a half-migrated database with its
# revision unchanged. That happened here, and the recovery was a restore.
#
# Existing unnamed constraints are unaffected; this governs what is emitted
# from now on.
target_metadata.naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


def sync_url() -> str:
    """A synchronous URL over the same file the application uses."""
    settings = get_settings()
    path = database_file(settings.database_url)
    if path is None:
        # A memory or server database. Fall back to the configured URL with the
        # async driver removed, rather than inventing a file.
        return settings.database_url.replace("+aiosqlite", "")
    return f"sqlite:///{path.as_posix()}"


def run_migrations_offline() -> None:
    context.configure(
        url=sync_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = sync_url()
    connectable = engine_from_config(
        section, prefix="sqlalchemy.", poolclass=pool.NullPool
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # SQLite cannot ALTER most things. Batch mode rebuilds the table
            # around the change, which is the only way a column type or a
            # constraint changes here at all.
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
